name: 05 Add and/or delete valid values

on:
  workflow_dispatch:
    inputs:
      ccnft_contract_address:
        description: 'CCNFT Contract Address'
        required: true
        type: string
      value:
        description: 'Value'
        required: true
        type: number
      action:
        description: 'Add value [true] | Delete value [false]'
        required: true
        type: boolean
        default: true

env:
  FOUNDRY_PROFILE: ci
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Add and/or delete valid values
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure Variables CONFIG_SEPOLIA
        run: |
          echo "CONFIG_SEPOLIA=--rpc-url=$SEPOLIA_RPC_URL --private-key=$PRIVATE_KEY --etherscan-api-key=$ETHERSCAN_API_KEY" >> $GITHUB_ENV

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Add valid value
        if: inputs.action == true
        run: |
          cast send ${{ inputs.ccnft_contract_address }} "addValidValues(uint256)" ${{ inputs.value }} $CONFIG_SEPOLIA


      - name: Delete valid value
        if: inputs.action == false
        run: |
          cast send ${{ inputs.ccnft_contract_address }} "deleteValidValues(uint256)" ${{ inputs.value }} $CONFIG_SEPOLIA
