name: 06 Approve contract value

on:
  workflow_dispatch:
    inputs:
      busd_contract_address:
        description: 'BUSD Contract Address'
        required: true
        type: string
      ccnft_contract_address:
        description: 'CCNFT Contract Address'
        required: true
        type: string
      approved_amount:
        description: 'Amount to approve'
        required: true
        type: number

env:
  FOUNDRY_PROFILE: ci
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Approve contract value
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure Variables CONFIG_SEPOLIA
        run: |
          echo "CONFIG_SEPOLIA=--rpc-url=$SEPOLIA_RPC_URL --private-key=$PRIVATE_KEY --etherscan-api-key=$ETHERSCAN_API_KEY" >> $GITHUB_ENV

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Approve ammount
        run: |
          cast send ${{ inputs.busd_contract_address }} "approve(address, uint256)" ${{ inputs.ccnft_contract_address }} ${{ inputs.approved_amount }} $CONFIG_SEPOLIA
