name: 02 Deploy contracts CCNF (SOJA & TRIGO) + BUSD [Script]

on:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Deploy contracts CCNF (SOJA & TRIGO) + BUSD [Script]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure Variables CONFIG_SEPOLIA
        run: |
          echo "CONFIG_SEPOLIA=--rpc-url=$SEPOLIA_RPC_URL --private-key=$PRIVATE_KEY --etherscan-api-key=$ETHERSCAN_API_KEY" >> $GITHUB_ENV

      - name: Configure Variables CONFIG_VERIFY
        run: |
          echo "CONFIG_VERIFY=$CONFIG_SEPOLIA --broadcast -vvvv --verify" >> $GITHUB_ENV

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Deploy CCNFT Soja
        run: |
          forge script script/DeployCCNFT.s.sol:DeployCCNFTSoja $CONFIG_VERIFY

      - name: Deploy CCNFT Trigo
        run: |
          forge script script/DeployCCNFT.s.sol:DeployCCNFTTrigo $CONFIG_VERIFY

      - name: Deploy ERC20 BUSD
        run: |
          forge script script/DeployBUSD.s.sol:DeployBUSD $CONFIG_VERIFY
